### PR TITLE
add c99 mode to cmakelist

### PR DESCRIPTION
**Pull request by MikeZhu92**
reference to https://github.com/glfw/glfw/issues/1560
This PR is to add the same patch to the owl library.

### CODE REVIEW

**Comment by ingowald** [comment]
Thank you!

**Comment by MikeZhu92** [comment]
Is this PR closed by accident 😄 ?

**Comment by ingowald** [comment]
i'll check.

**Comment by ingowald** [comment]
ooops. i had merged on the command-line, and apparently the last push didn't go through.
apologies, fixing right now

**Comment by ingowald** [comment]
should now be in both devel and master.
in my defense, it _got_ merged - just only on my laptop, not in the main repo :-/ 
ugh; apologies again.

**Pull request closed without merging**
