### PR TITLE
CMake system updates

### PR DESCRIPTION
**Pull request by lpisha**
There are three ways to use CUDA in a CMake project:
- **deprecated**, which means `find_cuda` and related scripts. This approach has been deprecated since 2018. CMake <= 3.7.
- **intermediate**, which uses first-class CUDA language support but CMake does not have a concept of CUDA architectures (they have to be set by manually setting compiler flags). 3.8 <= CMake <= 3.17.
- **modern**, which supports CUDA architectures. CMake >= 3.18.

Louis created this branch in February to add intermediate and modern CMake support to OWL. At the time, OWL **required** deprecated CMake CUDA, because various critical parent projects using OWL used deprecated CMake CUDA. Louis's parent project, as well as any other parent project which used intermediate or modern CMake and which needed to support Windows, was incompatible with deprecated CMake CUDA. However, after making these changes, the risk of breaking critical parent projects which depended on the deprecated build was deemed too great, even though the changes supported the deprecated build, so the changes were not merged.

In parallel, Nate updated OWL to intermediate CMake due to an issue where deprecated CMake caused Windows build tools to assume OWL always needed to be rebuilt. During this process, the critical parent projects were evidently updated to intermediate CMake.

Now, Louis removed support for deprecated CMake from this branch, and is merging it so that he can move his parent project back to mainline OWL. Most changes are minor; the only large change is the overhaul of `embed_ptx.cmake`. This supports both intermediate and modern style architectures, include paths on both platforms, and proper forwarding of other compiler flags. The additional features in this new version may not be needed for OWL proper, but they were needed in Louis's parent project using OWL, so they are being provided to the community.

This version is tested to work on CMake 3.8 (intermediate style) and 3.21 (modern style) on Linux (Debian), and CMake 3.9 (intermediate style) and 3.21 (modern style) on Windows (10, 3.9 -> VS 2017 and 3.21 -> VS 2019).

### CODE REVIEW

**Comment by ingowald** [comment]
First build gives me a warning about OWL_CUDA_ARCH not set - can we make that inform message? "warning" immediately makes one thing that something is probably broke, but think that 7.5 is perfectly adequate

**Comment by ingowald** [comment]
Other than that works perfectly fine for me - can anybody else run a test preferably on windows?

**Comment by lpisha** [comment]
> First build gives me a warning about OWL_CUDA_ARCH not set - can we make that inform message? "warning" immediately makes one thing that something is probably broke, but think that 7.5 is perfectly adequate

It's a warning because if the user's GPU is Pascal or earlier, the PTX compiled for Turing probably won't work, and if the user's GPU is Ampere, the PTX compiled for Turing may not be as efficient as PTX compiled for Ampere. It's PTX, not SASS, but there may still be differences between major versions.

In my parent project, there are scripts to detect the user's GPUs and automatically determine the appropriate architecture, but these assume the build machine is the target machine.

If you still would prefer it be a message rather than a warning, I'm happy to change it.

**Comment by ingowald** [comment]
Sure; I get the "want to match the HW arch" reason; in particular for Ampere I've seen quite some difference between compiling for 75 vs 83, so that makes sense; and I also get the "you're in hot water if you got too old HW" problem - we've definitely had users with pre-pascal HW, though, in which case even the 75 default would be problematic :-/. 
Auto-detecting during compile time would probably be my favorite for now - I'd expect the "redistribution" case to be rather unlikely for now, and even if a user were to do that, for the kind of users that would go that far I'd also expect _those_ users then also specify explicitly what they want to have. So if "default to build system config, with explicit override via cmake flag" would clearly be my favorite - it'd work on arbitrarily old platforms, would automatically pick the best by default, and "only" require (some) extra work for those expert users that want to redistribute.

Another option would be to look into multi-target compilation; I've reached out to some, but not gotten reply yet.

**Comment by ingowald** [comment]
Either way I'd not make it a warning, but pick the best default we can come up with, and then make it an informatoin message. Maybe double-check the results from PTX compilatoin and give a better warning if the compiled PTX code doesn't match, too - but definitely not have the default be a warning .... that'll just scare off most users, in particular those that wouldn't even know or care about that problem.

**Comment by ingowald** [comment]
Merged into devel; added tag "before-merging-louis-modern-cmake-branch" before merging, so can always go back if we need to.

**Pull request merged**
